name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.floofy.dev -u august --password-stdin
      - name: Build
        run: docker build -t registry.floofy.dev/nino/cluster-operator:${{github.sha}} .
      - name: Push
        run: docker push registry.floofy.dev/nino/cluster-operator:${{github.sha}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Set image
        run: |
          kubectl set image deployment/nino-prod-operator beta-operator=registry.floofy.dev/mika/cluster-operator:${{github.sha}}
          kubectl set image deployment/nino-edge-operator premium-operator=registry.floofy.dev/mika/cluster-operator:${{github.sha}}
      - name: Rollout status
        run: |
          kubectl rollout status deployment/nino-prod-operator
          kubectl rollout status deployment/nino-edge-operator
