name: Docker Hub Publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u auguwu --password-stdin
      - name: Build
        run: docker build -t noelware/cluster-operator:${{github.sha}} .
      - name: Push
        run: docker push noelware/cluster-operator:${{github.sha}}
